version: "3.9"
services:
  frontend:
    container_name: biscuitsbutton-web
    build: ./the-button-web
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    container_name: biscuitsbutton-server
    build: ./the-button-server
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@biscuitsbutton-postgres:5432/${POSTGRES_DB}
      - BUTTON_EXPIRY=${BUTTON_EXPIRY}
    volumes:
      - ./users.json:/app/users.json
  tunnel:
    container_name: biscuitsbutton-cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
  postgres:
    container_name: biscuitsbutton-postgres
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
