version: "3.9"
services:
  frontend:
    container_name: biscuitsbutton-web
    build: ./the-button-web
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    container_name: biscuitsbutton-server
    build: ./the-button-server
    restart: unless-stopped
  tunnel:
    container_name: biscuitsbutton-cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
